export const TYPES = {
  TRANSLATOR: Symbol('TRANSLATOR'),
  TRANSLATION_SERVICE: Symbol('TRANSLATION_SERVICE'),
  TRANSLATION: Symbol('TRANSLATION'),
  TRANSLATIONS: Symbol('TRANSLATIONS'),
  STORE: Symbol('STORE'),
  IS_USER_FIRST_VISIT_USE_CASE: Symbol('IS_USER_FIRST_VISIT_USE_CASE'),
  SET_USER_FIRST_VISIT_USE_CASE: Symbol('SET_USER_FIRST_VISIT_USE_CASE'),
  WALL_REPOSITORY: Symbol('WALL_REPOSITORY'),
  FIREBASE: Symbol('FIREBASE'),
  RX_FIRE: Symbol('RX_FIRE')
}
