export const TYPES = {
  TRANSLATOR: Symbol('TRANSLATOR'),
  TRANSLATION_SERVICE: Symbol('TRANSLATION_SERVICE'),
  TRANSLATION: Symbol('TRANSLATION'),
  TRANSLATIONS: Symbol('TRANSLATIONS'),
  STORE: Symbol('STORE')
}
